import { lstatSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { SecretVault, SecretVaultError } from "../src/core/secrets/secret-vault.ts";

describe("SecretVault", () => {
	const tempDirs: string[] = [];

	afterEach(() => {
		for (const dir of tempDirs.splice(0)) rmSync(dir, { recursive: true, force: true });
	});

	function createVault(onEnvironmentChanged?: () => void): { root: string; vault: SecretVault } {
		const root = mkdtempSync(join(tmpdir(), "pi-secret-vault-"));
		tempDirs.push(root);
		return {
			root,
			vault: new SecretVault({ agentDir: join(root, "agent"), scryptN: 1_024, onEnvironmentChanged }),
		};
	}

	it("encrypts values and metadata at rest, then unlocks only with the passphrase", async () => {
		const { vault } = createVault();
		const passphrase = "correct horse battery staple";
		const secret = "private-token-marker";

		await vault.initialize(passphrase);
		await vault.upsertProfile("project-dev", "Development credentials", [{ name: "API_TOKEN", value: secret }]);

		const serialized = readFileSync(vault.vaultPath, "utf8");
		expect(serialized).not.toContain(passphrase);
		expect(serialized).not.toContain(secret);
		expect(serialized).not.toContain("API_TOKEN");
		expect(serialized).not.toContain("project-dev");
		if (process.platform !== "win32") expect(lstatSync(vault.vaultPath).mode & 0o777).toBe(0o600);

		vault.lock();
		await expect(vault.listProfiles()).rejects.toMatchObject({ code: "not_unlocked" });
		await expect(vault.unlock("wrong-passphrase")).rejects.toMatchObject({ code: "unlock_failed" });
		await vault.unlock(passphrase);
		expect(await vault.listProfiles()).toEqual([
			expect.objectContaining({
				profile: "project-dev",
				description: "Development credentials",
				variableNames: ["API_TOKEN"],
			}),
		]);
	});

	it("materializes deterministic private dotenv and invalidates it when values change", async () => {
		const { vault } = createVault();
		await vault.initialize("a sufficiently long passphrase");
		await vault.upsertProfile("service", undefined, [
			{ name: "API_TOKEN", value: "quoted\nsecret" },
			{ name: "CLIENT_ID", value: "client-1" },
		]);
		const destination = vault.getManagedEnvPath("service");

		const materialized = await vault.materializeEnv("service", destination, { managed: true });
		expect(materialized.variableNames).toEqual(["API_TOKEN", "CLIENT_ID"]);
		expect(readFileSync(destination, "utf8")).toBe(
			'# pi-secret-store:v1 profile=service\n# Generated by Pi. Do not edit, inspect, source as shell code, or commit.\nAPI_TOKEN="quoted\\nsecret"\nCLIENT_ID="client-1"\n',
		);
		if (process.platform !== "win32") expect(lstatSync(destination).mode & 0o777).toBe(0o600);

		await vault.upsertProfile("service", undefined, [{ name: "API_TOKEN", value: "replacement" }]);
		expect(() => lstatSync(destination)).toThrow();
	});

	it("refuses unmanaged replacement and symlink destinations unless the owner path is explicitly replaceable", async () => {
		const { root, vault } = createVault();
		await vault.initialize("another strong passphrase");
		await vault.upsertProfile("service", undefined, [{ name: "TOKEN", value: "secret" }]);
		const destination = join(root, ".env");
		writeFileSync(destination, "EXISTING=true\n");

		await expect(vault.materializeEnv("service", destination)).rejects.toMatchObject({
			code: "destination_conflict",
		});
		await expect(vault.materializeEnv("service", destination, { allowReplaceUnmanaged: true })).rejects.toMatchObject(
			{
				code: "destination_conflict",
			},
		);
		writeFileSync(destination, "CHANGED=true\n");
		await expect(
			vault.materializeEnv("service", destination, {
				allowReplaceUnmanaged: true,
				expectedUnmanagedContent: "EXISTING=true\n",
			}),
		).rejects.toMatchObject({ code: "destination_conflict" });
		expect(readFileSync(destination, "utf8")).toBe("CHANGED=true\n");
		writeFileSync(destination, "EXISTING=true\n");
		await vault.materializeEnv("service", destination, {
			allowReplaceUnmanaged: true,
			expectedUnmanagedContent: "EXISTING=true\n",
		});
		expect(readFileSync(destination, "utf8")).toContain('TOKEN="secret"');

		if (process.platform !== "win32") {
			const target = join(root, "target.env");
			const link = join(root, "linked.env");
			writeFileSync(target, "SAFE=true\n");
			symlinkSync(target, link);
			await expect(vault.materializeEnv("service", link, { allowReplaceUnmanaged: true })).rejects.toBeInstanceOf(
				SecretVaultError,
			);
			expect(readFileSync(target, "utf8")).toBe("SAFE=true\n");

			const workspace = join(root, "workspace");
			const outside = join(root, "outside");
			mkdirSync(workspace);
			mkdirSync(join(outside, "nested"), { recursive: true });
			symlinkSync(outside, join(workspace, "redirect"), "dir");
			await vault.replaceProfileDocument("escape", undefined, "TOKEN=secret\n", {
				workspace,
				envFile: "redirect/nested/.env",
			});
			const escaped = await vault.resolveBindingForWorkspace(workspace, "escape");
			await expect(vault.materializeEnv("escape", escaped.destination)).rejects.toMatchObject({
				code: "destination_invalid",
			});
		}
	});

	it("merges and removes bounded profile variables without returning values", async () => {
		const { vault } = createVault();
		await vault.initialize("one more strong passphrase");
		await vault.upsertProfile("service", undefined, [
			{ name: "A_TOKEN", value: "a" },
			{ name: "B_TOKEN", value: "b" },
		]);
		await vault.upsertProfile("service", undefined, [{ name: "B_TOKEN", value: "new-b" }]);
		expect((await vault.listProfiles())[0]?.variableNames).toEqual(["A_TOKEN", "B_TOKEN"]);
		const materializedPath = vault.getManagedEnvPath("service");
		await vault.materializeEnv("service", materializedPath, { managed: true });
		await expect(vault.removeProfile("service", ["MISSING_TOKEN"])).rejects.toMatchObject({
			code: "invalid_variable",
		});
		expect(readFileSync(materializedPath, "utf8")).toContain('B_TOKEN="new-b"');

		const partial = await vault.removeProfile("service", ["A_TOKEN"]);
		expect(partial).toMatchObject({ removedProfile: false, removedVariableNames: ["A_TOKEN"] });
		const final = await vault.removeProfile("service");
		expect(final).toMatchObject({ removedProfile: true, removedVariableNames: ["B_TOKEN"] });
		expect(await vault.listProfiles()).toEqual([]);
	});

	it("rejects Windows device names on every platform", () => {
		const { vault } = createVault();
		expect(() => vault.getManagedEnvPath("CON")).toThrowError(expect.objectContaining({ code: "invalid_profile" }));
		expect(() => vault.getManagedEnvPath("con.profile")).toThrowError(
			expect.objectContaining({ code: "invalid_profile" }),
		);
	});

	it("preserves an owner dotenv document, remembers its workspace binding, and activates its environment", async () => {
		const environmentChanged = vi.fn();
		const { root, vault } = createVault(environmentChanged);
		await vault.initialize("binding cache passphrase");
		const secret = "opaque-owner-value-marker";
		const document = `# kept owner comment\nAPI_TOKEN=${secret}\nREGION='us-east-1'\n`;
		await vault.replaceProfileDocument("project", "Project credentials", document, {
			workspace: root,
			envFile: ".env.local",
		});

		const profiles = await vault.listProfiles();
		expect(profiles[0]).toMatchObject({
			profile: "project",
			variableNames: ["API_TOKEN", "REGION"],
			bindings: [{ workspace: root, envFile: ".env.local" }],
		});
		const binding = await vault.resolveBindingForWorkspace(join(root, "nested"), "project");
		expect(binding).toMatchObject({ profile: "project", envFile: ".env.local" });
		expect(binding.destination).toBe(join(root, ".env.local"));
		expect(vault.getEnvironmentForCwd(root)).toEqual({});
		expect(environmentChanged).not.toHaveBeenCalled();

		await vault.materializeEnv("project", binding.destination);
		expect(readFileSync(binding.destination, "utf8")).toBe(
			`# pi-secret-store:v1 profile=project\n# Generated by Pi. Do not edit, inspect, source as shell code, or commit.\n${document}`,
		);
		expect(vault.getEnvironmentForCwd(root)).toMatchObject({ API_TOKEN: secret, REGION: "us-east-1" });
		expect(vault.redactSensitiveText(`response=${secret}`)).toBe("response=[REDACTED]");
		expect(environmentChanged).toHaveBeenCalledOnce();

		const replacement = "replacement-owner-value-marker";
		await vault.replaceProfileDocument("project", "Project credentials", document.replace(secret, replacement), {
			workspace: root,
			envFile: ".env.local",
		});
		expect(vault.getEnvironmentForCwd(root)).toEqual({});
		expect(() => lstatSync(binding.destination)).toThrow();
		expect(environmentChanged).toHaveBeenCalledTimes(3);
		await vault.materializeEnv("project", binding.destination);
		expect(vault.getEnvironmentForCwd(root)).toMatchObject({ API_TOKEN: replacement });
		expect(environmentChanged).toHaveBeenCalledTimes(4);

		vault.lock();
		expect(vault.getEnvironmentForCwd(root)).toEqual({});
		expect(environmentChanged).toHaveBeenCalledTimes(5);
	});

	it("rejects bindings outside the workspace and requires a profile when bindings are ambiguous", async () => {
		const { root, vault } = createVault();
		await vault.initialize("ambiguous binding passphrase");
		expect(() => vault.resolveBindingTarget(root, "../outside.env")).toThrowError(
			expect.objectContaining({ code: "destination_invalid" }),
		);

		await vault.replaceProfileDocument("first", undefined, "TOKEN=first-value\n", {
			workspace: root,
			envFile: ".env.first",
		});
		await vault.replaceProfileDocument("second", undefined, "TOKEN=second-value\n", {
			workspace: root,
			envFile: ".env.second",
		});
		await expect(vault.resolveBindingForWorkspace(root)).rejects.toMatchObject({ code: "ambiguous_binding" });
		expect(await vault.resolveBindingForWorkspace(root, "second")).toMatchObject({ envFile: ".env.second" });
	});
});
