import type { ImageContent, TextContent, Usage } from "@caupulican/pi-ai/types";
import type { AgentMessage, AgentMessageOrigin } from "../types.ts";

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
	/** Provenance for host-synthesized messages; absent means provider/conversation-native. */
	origin?: AgentMessageOrigin;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

/** Sparse history retained after a full session-replacement compaction. */
export interface CompactionRetention {
	mode: "original-user";
	/** User-message entry that anchors the owner's original request on the active branch. */
	userEntryId: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Optional non-contiguous retention policy for provider-native session replacement. */
	retention?: CompactionRetention;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** Usage from every LLM call that produced or verified this summary. */
	usage?: Usage;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** Usage from every LLM call that produced this summary. */
	usage?: Usage;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry
	| SessionLifecycleEntry;

export interface RequestSnapshotEntry extends SessionEntryBase {
	type: "request_snapshot";
	requestId: string;
	reason: "initial" | "resume" | "change";
	api: string;
	provider: string;
	modelId: string;
	effectiveConfigFingerprint: string;
	systemFingerprint: string;
	toolsFingerprint: string;
	historyFingerprint: string;
	messageEntryIds: string[];
	/**
	 * The reasoning level the request was sent with, when the host resolved one. Kept in the clear
	 * (the effective-config fingerprint folds it) so a session census can count the requests a
	 * request-local policy lowered, such as host-started turns.
	 */
	reasoning?: string;
	/**
	 * Whether this request's provider-visible prefix is exactly the previous request's on the same lane
	 * (model): true when the system prompt, the tools and every message the previous request sent are
	 * unchanged and in place; false when something already sent changed; "unknown" for the first request
	 * a process sees on a lane. A cold cache on an intact prefix is the provider's; on a broken one, ours.
	 */
	prefixIntact?: boolean | "unknown";
	/** Where the prefix first differs: -1 for the system prompt or tools, else the message index. */
	firstDivergentIndex?: number;
	/** What first differs: `system`, `tools`, `removed`, or the message's role (`custom:<type>` for records). */
	firstDivergentKind?: string;
	/** How many provider messages the request carried. */
	messageCount?: number;
}

export type ProviderRequestOutcome = "completed" | "aborted" | "error" | "interrupted";

export interface ProviderRequestTerminalEntry extends SessionEntryBase {
	type: "provider_request_terminal";
	requestId: string;
	outcome: ProviderRequestOutcome;
	/** Canonical assistant response for every transport terminal except a recovered interruption. */
	assistantMessageEntryId?: string;
}

export interface ForegroundToolStartEntry extends SessionEntryBase {
	type: "foreground_tool_start";
	requestId: string;
	assistantMessageEntryId: string;
	callId: string;
	toolName: string;
}

export interface ForegroundToolTerminalEntry extends SessionEntryBase {
	type: "foreground_tool_terminal";
	requestId: string;
	assistantMessageEntryId: string;
	callId: string;
	toolName: string;
	outcome: "success" | "error" | "cancelled";
	resultMessageEntryId: string;
	errorKind?: "tool_failure" | "operation_outcome";
}

export interface CompactionStartEntry extends SessionEntryBase {
	type: "compaction_start";
	compactionId: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Estimated tokens handed to the summarizer, for the census gate against `tokensBefore`. */
	summarizerInputTokens?: number;
}

export interface CompactionEndEntry extends SessionEntryBase {
	type: "compaction_end";
	compactionId: string;
	/** `fallback`: a facts-only checkpoint was applied because no summarizer accepted a summary. */
	outcome: "success" | "failure" | "cancelled" | "interrupted" | "fallback";
	compactionEntryId?: string;
	error?: string;
}

export type SessionLifecycleEntry =
	| RequestSnapshotEntry
	| ProviderRequestTerminalEntry
	| ForegroundToolStartEntry
	| ForegroundToolTerminalEntry
	| CompactionStartEntry
	| CompactionEndEntry;
