export const DEPENDENCY_FORKS = [
	{
		original: "source-map-js", upstreamVersion: "1.2.2", name: "pi-source-map-codec", version: "1.2.2-pi.1",
		archive: "scripts/dependency-forks/sources/source-map-js-1.2.2.tar.gz",
		integrity: "sha512-KGj/8Y43x35aZVDtt+J4mK1hoLGHULMYfSkODJNQjNDC3oW1PqPoxMwo0pLUsWM/UEGzON/NxeHywEfNXNP3Vw==",
		directory: "vendor/pi-source-map-codec", main: "source-map.js", license: "BSD-3-Clause", dependencies: {},
		advisory: "GHSA-68fv-2mgg-jv7q", helpers: {},
		sourceFiles: ["source-map.js", "source-map.d.ts", ...["array-set", "base64-vlq", "base64", "binary-search", "mapping-list", "quick-sort", "source-map-consumer", "source-map-generator", "source-node", "util"].map((name) => `lib/${name}.js`), ...["source-map-consumer", "source-map-generator", "source-node"].map((name) => `lib/${name}.d.ts`)],
		patches: [
			{ file: "lib/source-map-consumer.js", before: " *     line number is 1-based. \n", after: " *     line number is 1-based.\n" },
			{ file: "lib/source-map-generator.js", before: "if (sourceRoot !== null)", after: "if (sourceRoot != null)" },
			{ file: "lib/source-map-consumer.js", before: "section.generatedOffset.generatedColumn);", after: "(section.generatedOffset.generatedColumn - 1));" },
			{ file: "lib/source-map-consumer.js", before: "      // Only consider this section if the requested source is in the list of\n      // sources of the consumer.\n      if (section.consumer._findSourceIndex(util.getArg(aArgs, 'source')) === -1) {\n        continue;\n      }\n", after: "" },
			{ file: "lib/source-map-consumer.js", before: "if (generatedPosition)", after: "if (generatedPosition.line != null && generatedPosition.column != null)" },
			{ file: "lib/source-map-consumer.js", before: "section.generatedOffset.generatedLine === generatedPosition.line", after: "generatedPosition.line === 1" },
			{ file: "lib/source-map-consumer.js", before: "section.generatedOffset.generatedLine === mapping.generatedLine", after: "mapping.generatedLine === 1" },
			{ file: "lib/source-map-consumer.js", before: "if (mapping.name)", after: "if (mapping.name != null)" },
			{ file: "lib/source-map-consumer.js", before: "var source = section.consumer._sources.at(mapping.source);\n        if(source !== null) {\n          source = util.computeSourceURL(section.consumer.sourceRoot, source, this._sourceMapURL);\n        }\n        this._sources.add(source);\n        source = this._sources.indexOf(source);", after: "var source = null;\n        if (mapping.source != null) {\n          source = section.consumer._sources.at(mapping.source);\n          source = util.computeSourceURL(section.consumer.sourceRoot, source, this._sourceMapURL);\n          this._sources.add(source);\n          source = this._sources.indexOf(source);\n        }" },
		],
	},
	{
		original: "magicast", upstreamVersion: "0.5.4", name: "pi-config-transform", version: "0.5.4-pi.1",
		archive: "scripts/dependency-forks/sources/magicast-0.5.4.tgz",
		integrity: "sha512-llBEhWm1SacoRwgHUoQJYtwp4PBLF4faQi5TCpIGyGs9n4y5+juI0tDgyKIfpqxckRHaHzouUEph3THklWh03w==",
		directory: "vendor/pi-config-transform", main: "./dist/index.js", license: "MIT",
		dependencies: { "@babel/parser": "7.29.8", "@babel/types": "7.29.8", "source-map-js": "file:../pi-source-map-codec" },
		advisory: "GHSA-68fv-2mgg-jv7q", helpers: {},
		sourceFiles: ["dist/builders-pgs2P7Vh.js", "dist/core.js", "dist/helpers.js", "dist/index.js", "dist/core.d.ts", "dist/helpers.d.ts", "dist/index.d.ts", "dist/types-BneF6GqE.d.ts"],
		patches: [
			{ file: "dist/builders-pgs2P7Vh.js", before: "import * as babelParser from \"@babel/parser\";", after: "import * as babelParser from \"@babel/parser\";\nimport * as import_source_map from \"source-map-js\";" },
			{ file: "dist/builders-pgs2P7Vh.js", region: { start: "//#region node_modules/.pnpm/source-map-js@1.2.1/node_modules/source-map-js/lib/base64.js", end: "const n$2 = namedTypes$1;", sha256: "a556521a7d147f37354b7d166cb5407c4e9eeb367f1301fea7dd45db2252cbec" }, after: "//#region vendor/recast/lib/util.ts\n" },
		],
	},
	{
		original: "braces", upstreamVersion: "3.0.3", name: "pi-pattern-guard", version: "3.0.3-pi.1",
		archive: "scripts/dependency-forks/sources/braces-3.0.3.tar.gz",
		integrity: "sha512-yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==",
		directory: "vendor/pi-pattern-guard", main: "index.js", license: "MIT",
		dependencies: { "fill-range": "7.1.1" },
		advisory: "GHSA-vfj7-8cjw-p6xm",
		helpers: { "lib/pattern-policy.cjs": "scripts/dependency-forks/pattern-policy.cjs" },
		patches: [
			{ file: "lib/parse.js", before: "const stringify = require('./stringify');", after: "const stringify = require('./stringify');\nconst { pushPatternBlock } = require('./pattern-policy.cjs');" },
			{ file: "lib/parse.js", before: "      stack.push(block);", after: "      pushPatternBlock(stack, block);", count: 2 },
			... ["compile", "stringify", "expand"].map((owner) => ({ file: `lib/${owner}.js`, before: "'use strict';", after: "'use strict';\n\nconst { validatePatternStructure } = require('./pattern-policy.cjs');" })),
			{ file: "lib/compile.js", before: "const compile = (ast, options = {}) => {", after: "const compile = (ast, options = {}) => {\n  validatePatternStructure(ast);\n  const budget = createPatternBudget();" },
			{ file: "lib/stringify.js", before: "module.exports = (ast, options = {}) => {", after: "module.exports = (ast, options = {}) => {\n  validatePatternStructure(ast);" },
			{ file: "lib/expand.js", before: "const expand = (ast, options = {}) => {", after: "const expand = (ast, options = {}) => {\n  validatePatternStructure(ast);\n  const budget = createPatternBudget();" },
			{ file: "lib/compile.js", before: "const fill = require('fill-range');", after: "const { fillPatternRange, createPatternBudget, appendPatternOutput, joinPatternOutput } = require('./pattern-policy.cjs');" },
			{ file: "lib/compile.js", before: "fill(...args, { ...options, wrap: false, toRegex: true, strictZeros: true })", after: "fillPatternRange(args, { ...options, wrap: false, toRegex: true, strictZeros: true }, budget)" },
			{ file: "lib/compile.js", before: "return prefix + node.value;", after: "return joinPatternOutput(prefix, node.value);", count: 2 },
			{ file: "lib/compile.js", before: "return invalid ? prefix + node.value :", after: "return invalid ? joinPatternOutput(prefix, node.value) :", count: 2 },
			{ file: "lib/compile.js", before: "`(${range})`", after: "joinPatternOutput('(', range, ')')" },
			{ file: "lib/compile.js", before: "let output = '';", after: "const output = [];\n    let outputLength = 0;" },
			{ file: "lib/compile.js", before: "output += walk(child, node);", after: "outputLength = appendPatternOutput(output, walk(child, node), outputLength);" },
			{ file: "lib/compile.js", before: "return output;", after: "return output.join('');" },
			{ file: "lib/expand.js", before: "const fill = require('fill-range');", after: "const { fillPatternRange, createPatternBudget, appendPatternResult } = require('./pattern-policy.cjs');" },
			{ file: "lib/expand.js", before: "const append = (queue = '', stash = '', enclose = false) => {", after: "const append = (queue = '', stash = '', enclose = false, budget) => {" },
			{ file: "lib/expand.js", before: "    return enclose ? utils.flatten(stash).map(ele => `{${ele}}`) : stash;", after: "    const values = enclose ? utils.flatten(stash).map(ele => `{${ele}}`) : stash;\n    for (const value of values) appendPatternResult(result, value, budget);\n    return result;" },
			{ file: "lib/expand.js", before: "result.push(append(value, stash, enclose));", after: "appendPatternResult(result, append(value, stash, enclose, budget), budget);" },
			{ file: "lib/expand.js", before: "result.push(Array.isArray(ele) ? append(item, ele, enclose) : item + ele);", after: "appendPatternResult(result, Array.isArray(ele) ? append(item, ele, enclose, budget) : item + ele, budget);" },
			{ file: "lib/expand.js", before: "  const rangeLimit = options.rangeLimit === undefined ? 1000 : options.rangeLimit;\n", after: "" },
			{ file: "lib/expand.js", before: "      if (utils.exceedsLimit(...args, options.step, rangeLimit)) {\n        throw new RangeError('expanded array length exceeds range limit. Use options.rangeLimit to increase or disable the limit.');\n      }\n\n      let range = fill(...args, options);", after: "      let range = fillPatternRange(args, options, budget);" },
			{ file: "lib/utils.js", before: "/**\n * Find a node of the given type\n */\n\nexports.exceedsLimit = (min, max, step = 1, limit) => {\n  if (limit === false) return false;\n  if (!exports.isInteger(min) || !exports.isInteger(max)) return false;\n  return ((Number(max) - Number(min)) / Number(step)) >= limit;\n};\n\n", after: "" },
			{ file: "lib/expand.js", before: "append(q.pop(), stringify(node, options))", after: "append(q.pop(), stringify(node, options), false, budget)" },
			{ file: "lib/expand.js", before: "append(q.pop(), ['{}'])", after: "append(q.pop(), ['{}'], false, budget)" },
			{ file: "lib/expand.js", before: "append(q.pop(), range)", after: "append(q.pop(), range, false, budget)" },
			{ file: "lib/expand.js", before: "append(q.pop(), queue, enclose)", after: "append(q.pop(), queue, enclose, budget)" },
			{ file: "lib/expand.js", before: "append(queue.pop(), child.value)", after: "append(queue.pop(), child.value, false, budget)" },
		],
	},
	{
		original: "node-forge", upstreamVersion: "1.4.0", name: "pi-certificate-codec", version: "1.4.0-pi.1",
		archive: "scripts/dependency-forks/sources/node-forge-1.4.0.tar.gz",
		integrity: "sha512-LarFH0+6VfriEhqMMcLX2F7SwSXeWwnEAJEsYm5QKWchiVYVvJyV9v7UDvUv+w5HO23ZpQTXDv/GxdDdMyOuoQ==",
		directory: "packages/coding-agent/examples/extensions/sandbox/vendor/pi-certificate-codec",
		main: "lib/index.js", license: "BSD-3-Clause", dependencies: {},
		advisory: "GHSA-86w9-cpqp-85rv",
		helpers: { "lib/digest-policy.cjs": "scripts/dependency-forks/digest-policy.cjs" },
		patches: [
			{ file: "lib/rsa.js", before: "var forge = require('./forge');", after: "var forge = require('./forge');\nvar hasCanonicalDigestAlgorithm = require('./digest-policy.cjs').hasCanonicalDigestAlgorithm;" },
			{ file: "lib/rsa.js", before: "obj.value.length !== 2) {", after: "!hasCanonicalDigestAlgorithm(obj, asn1)) {" },
		],
	},
];
