export const DEFAULT_GOAL_CONTINUE_MAX_TURNS = 20;
export const DEFAULT_GOAL_CONTINUE_MAX_STALL_TURNS = 20;
export const MAX_GOAL_CONTINUE_MAX_TURNS = 20;
export const MAX_GOAL_CONTINUE_MAX_STALL_TURNS = 100;
