#!/usr/bin/env node
/**
 * Generates docs/architecture.md: one paragraph per controller and per extracted session module
 * under packages/coding-agent/src/core, taken from each file's own header comment, plus whether a
 * test file of the same name exists. Line counts are deliberately not in the map (they would make
 * it stale on every edit; the coordinator's line ratchet lives in check-coordinator-boundaries).
 * The map is the bus-factor artifact of the harness ratchet model: whoever reads it holds the
 * whole design at the level of who owns what.
 *
 *   node scripts/architecture-map.mjs            # writes docs/architecture.md
 *   node scripts/architecture-map.mjs --check    # exits 1 when the file is stale
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const core = join(root, "packages/coding-agent/src/core");
const tests = join(root, "packages/coding-agent/test");
const out = join(root, "docs/architecture.md");

function headerSentence(path) {
	const text = readFileSync(path, "utf8");
	const match = text.match(/^\/\*\*\s*\n([\s\S]*?)\*\//);
	if (!match) return "(no header comment)";
	const body = match[1]
		.split("\n")
		.map((line) => line.replace(/^\s*\*\s?/, "").trim())
		.filter((line) => line && !line.startsWith("@"))
		.join(" ");
	const sentence = body.match(/^(.*?[.!?])(\s|$)/);
	return (sentence ? sentence[1] : body).slice(0, 320);
}

const files = readdirSync(core)
	.filter((name) => name.endsWith(".ts") && !name.endsWith(".d.ts"))
	.filter((name) => name.endsWith("-controller.ts") || name.startsWith("agent-session") || name === "capability-tier.ts")
	.sort();

const rows = files.map((name) => {
	const path = join(core, name);
	const testName = name.replace(/\.ts$/, ".test.ts");
	const hasTest = existsSync(join(tests, testName)) || existsSync(join(tests, "suite", testName));
	return { name, sentence: headerSentence(path), hasTest };
});

const lines = [
	"# Architecture map",
	"",
	"Generated by `node scripts/architecture-map.mjs` from the header comment of every controller and",
	"session module under `packages/coding-agent/src/core`. Regenerate after adding or extracting one;",
	"`--check` fails when this file is stale. The invariants these modules enforce are in",
	"`docs/doctrine.md`.",
	"",
	"| Module | Own test | What it owns |",
	"|---|---|---|",
	...rows.map((row) => `| \`${row.name}\` | ${row.hasTest ? "yes" : "no"} | ${row.sentence.replace(/\|/g, "\\|")} |`),
	"",
	`${rows.length} modules, ${rows.filter((row) => row.hasTest).length} with a test file of the same name.`,
	"",
];
const rendered = `${lines.join("\n")}\n`;
if (process.argv.includes("--check")) {
	const current = existsSync(out) ? readFileSync(out, "utf8") : "";
	if (current !== rendered) {
		console.error("architecture-map: docs/architecture.md is stale; run node scripts/architecture-map.mjs");
		process.exit(1);
	}
	console.log("architecture-map: up to date");
} else {
	writeFileSync(out, rendered);
	console.log(`architecture-map: wrote ${out} (${rows.length} modules)`);
}
